version: '3.8'

services:
  api-gateway:
    build: ./backend/gateway
    ports:
      - "8000:8000"
    environment:
      - USER_MANAGER_URL=http://user-manager:8001
    depends_on:
      - user-manager
    networks:
      - microservices

  user-manager:
    build: ./backend/user-manager
    ports:
      - "8001:8001"
    environment:
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_CLIENT_X509_CERT_URL=${FIREBASE_CLIENT_X509_CERT_URL}
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
